### ISSUE TITLE
error calling ne: incompatible types for comparison

### ISSUE THREAD

**Issue by davidli18** [ananace/personal-charts#1]
hi, thanks for your job. when i use matrix-synapse charts, i got a error:
error calling ne: incompatible types for comparison
the error is in worker-configuration.yaml file
`{{- if $config.name -}}

{{-   if (ne $config.replicaCount 1) -}}

{{-     fail "Replica count must be 1 if a worker has a unique name." -}}

{{-   end }}`
when i change the code to  {{-   if (ne $config.replicaCount 1.0) -}}
the error  disappeared. so maybe it's a issue, thank you again.

**Comment by ananace** [comment]
I added a type conversion on that comparison, so it shouldn't happen again. Though how the replica count could be something other than an integer to begin with is odd.
