### ISSUE TITLE
Depricated Annotation in Service: matrix-synapse-postgresql-hl, please remove

### ISSUE THREAD

**Issue by M-A-X-I-M** [ananace/personal-charts#6]
While Upgrading k8s from 1.25.X -> 1.27.X, got this error.

`some check failed in cluster upgrade: this cluster has deprecated service list: map[matrix-synapse-postgresql-hl:{}] with deprecated annotation list [tolerate-unready-endpoints] `

The annotation **tolerate-unready-endpoints** need to be removed from the service **matrix-synapse-postgresql-hl**

**Comment by ananace** [comment]
This looks like an upstream issue in the bitnami chart for Postgres, please report it there instead;

https://github.com/bitnami/charts/blob/main/bitnami/postgresql/templates/primary/svc-headless.yaml#L22

**Comment by M-A-X-I-M** [comment]
i reported it on bitnami's github: https://github.com/bitnami/charts/issues/27435
they fixed it.
you need to bump your bitnami's dependencies up in your chart.yaml I think
